In [2]:
import numpy as np
import pandas as pd
import folium as fm
# from mpl_toolkits.basemap import BaseMap as BaseMap
import matplotlib.animation as animation
import imgkit as ik
imgkit_config = ik.config(wkhtmltoimage='/usr/local/bin/wkhtmltoimage')
import pgeocode
import selenium.webdriver
import time

In [3]:
# nomi = pgeocode.Nominatim('us')
# info = nomi.query_postal_code("19153")

"""
dist = pgeocode.GeoDistance('fr')
dist.query_postal_code("75013", "69006")
"""

'\ndist = pgeocode.GeoDistance(\'fr\')\ndist.query_postal_code("75013", "69006")\n'

In [4]:
basepath = '/Users/chenyuxin/DataHack2020/data/'

In [5]:
dph_od_incident_counts = pd.read_csv(basepath+'dph_od_incident_counts.csv', header='infer')
dph_od_resident_counts = pd.read_csv(basepath+'dph_od_resident_counts.csv', header='infer')
dph_dash_ems_naloxone_zip = pd.read_csv(basepath+'dph_dash_ems_naloxone_zip.csv', header='infer')
psp_incidents = pd.read_csv(basepath+'dph_dash_ems_naloxone_zip.csv', header='infer')

# psp = pd.read_csv('', header='infer')

In [6]:
dph_od_incident_counts.head()

,ZIPCODE,X2014Q1,X2014Q2,X2014Q3,X2014Q4,X2015Q1,X2015Q2,X2015Q3,X2015Q4,X2016Q1,...,X2016Q3,X2016Q4,X2017Q1,X2017Q2,X2017Q3,X2017Q4,X2018Q1,X2018Q2,X2018Q3,X2018Q4
0,19102,0,0,0,0,0,0,<6,0,<6,...,0,<6,<6,0,<6,<6,0,<6,<6,0
1,19103,<6,0,<6,0,0,0,0,0,0,...,<6,<6,<6,<6,<6,0,<6,<6,<6,<6
2,19104,<6,<6,<6,6,6,6,<6,<6,<6,...,<6,6,<6,6,9,8,<6,7,<6,8
3,19106,0,0,<6,<6,<6,0,0,<6,<6,...,<6,<6,<6,<6,<6,<6,<6,<6,<6,<6
4,19107,<6,<6,<6,<6,<6,<6,0,<6,6,...,<6,<6,<6,<6,<6,<6,<6,<6,<6,6

In [7]:
dph_od_resident_counts.head()

,Zip.Code,X2014Q1,X2014Q2,X2014Q3,X2014Q4,X2015Q1,X2015Q2,X2015Q3,X2015Q4,X2016Q1,...,X2016Q3,X2016Q4,X2017Q1,X2017Q2,X2017Q3,X2017Q4,X2018Q1,X2018Q2,X2018Q3,X2018Q4
0,19102,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,<6,0,0,<6,0
1,19103,0,0,<6,0,0,0,0,0,0,...,<6,0,<6,<6,0,<6,<6,<6,0,0
2,19104,<6,<6,<6,<6,7,<6,<6,7,<6,...,<6,7,<6,<6,<6,<6,<6,<6,6,8
3,19106,0,0,0,<6,0,0,0,0,0,...,<6,<6,<6,<6,<6,0,<6,0,<6,0
4,19107,<6,<6,0,<6,<6,<6,<6,<6,<6,...,<6,0,<6,<6,<6,<6,<6,<6,<6,<6

In [8]:
dph_dash_ems_naloxone_zip.head()

   Pickup.Zip.Code  Numebr.of.Records
0            19116                187
1            19154                281
2            19115                149
3            19114                233
4            19111                301

Assess

In [9]:
quarters = dph_od_incident_counts.columns[1:]

for q in quarters:
    unique_vals, counts = np.unique(dph_od_incident_counts[q].values, return_counts=True)
    
    count_sort_ind = np.argsort(-counts)
    
    print('sorted incidents by count across zip codes: {0}'.format(unique_vals[count_sort_ind]))
    print('corresponding counts across zip codes: {0}'.format(counts[count_sort_ind]))
    print('across quarter {0}, percent of incidents < 6: {1} \n'.format(q, 100*counts[count_sort_ind][0]/np.sum(counts[count_sort_ind])))

sorted incidents by count across zip codes: ['<6' '0' '6' '10' '15' '7' '8' '9']
corresponding counts across zip codes: [28 13  2  1  1  1  1  1]
across quarter X2014Q1, percent of incidents < 6: 58.333333333333336

sorted incidents by count across zip codes: ['<6' '0' '10' '8' '6' '11' '18' '7']
corresponding counts across zip codes: [25 12  3  3  2  1  1  1]
across quarter X2014Q2, percent of incidents < 6: 52.083333333333336

sorted incidents by count across zip codes: ['<6' '0' '6' '10' '19']
corresponding counts across zip codes: [33 11  2  1  1]
across quarter X2014Q3, percent of incidents < 6: 68.75

sorted incidents by count across zip codes: ['<6' '0' '8' '10' '6' '22' '7']
corresponding counts across zip codes: [32  7  3  2  2  1  1]
across quarter X2014Q4, percent of incidents < 6: 66.66666666666667

sorted incidents by count across zip codes: ['<6' '0' '7' '6' '9' '10' '13' '19']
corresponding counts across zip codes: [28 10  3  2  2  1  1  1]
across quarter X2015Q1, percent of incidents < 6: 58.333333333333336

sorted incidents by count across zip codes: ['<6' '0' '7' '10' '11' '23' '6' '8' '9']
corresponding counts across zip codes: [28 12  2  1  1  1  1  1  1]
across quarter X2015Q2, percent of incidents < 6: 58.333333333333336

sorted incidents by count across zip codes: ['<6' '0' '6' '9' '30' '7']
corresponding counts across zip codes: [33  9  2  2  1  1]
across quarter X2015Q3, percent of incidents < 6: 68.75

sorted incidents by count across zip codes: ['<6' '0' '7' '6' '8' '10' '12' '14' '21' '9']
corresponding counts across zip codes: [24 12  3  2  2  1  1  1  1  1]
across quarter X2015Q4, percent of incidents < 6: 50.0

sorted incidents by count across zip codes: ['<6' '7' '0' '8' '10' '11' '12' '22' '6' '9']
corresponding counts across zip codes: [29  6  5  2  1  1  1  1  1  1]
across quarter X2016Q1, percent of incidents < 6: 60.416666666666664

sorted incidents by count across zip codes: ['<6' '6' '0' '10' '7' '9' '13' '26' '8']
corresponding counts across zip codes: [32  4  3  2  2  2  1  1  1]
across quarter X2016Q2, percent of incidents < 6: 66.66666666666667

sorted incidents by count across zip codes: ['<6' '0' '7' '8' '39' '6' '9']
corresponding counts across zip codes: [32  5  5  3  1  1  1]
across quarter X2016Q3, percent of incidents < 6: 66.66666666666667

sorted incidents by count across zip codes: ['<6' '0' '6' '7' '9' '10' '13' '11' '12' '17' '52']
corresponding counts across zip codes: [26  4  4  3  3  2  2  1  1  1  1]
across quarter X2016Q4, percent of incidents < 6: 54.166666666666664

sorted incidents by count across zip codes: ['<6' '0' '8' '7' '9' '11' '13' '15' '23' '24' '53' '6']
corresponding counts across zip codes: [23  6  5  4  3  1  1  1  1  1  1  1]
across quarter X2017Q1, percent of incidents < 6: 47.916666666666664

sorted incidents by count across zip codes: ['<6' '0' '6' '8' '9' '10' '13' '11' '17' '19' '21' '59' '7']
corresponding counts across zip codes: [21  6  4  4  3  2  2  1  1  1  1  1  1]
across quarter X2017Q2, percent of incidents < 6: 43.75

sorted incidents by count across zip codes: ['<6' '9' '6' '7' '0' '11' '12' '14' '26' '61' '8']
corresponding counts across zip codes: [26  5  4  4  3  1  1  1  1  1  1]
across quarter X2017Q3, percent of incidents < 6: 54.166666666666664

sorted incidents by count across zip codes: ['<6' '8' '6' '0' '7' '10' '11' '25' '36' '9']
corresponding counts across zip codes: [28  6  4  3  2  1  1  1  1  1]
across quarter X2017Q4, percent of incidents < 6: 58.333333333333336

sorted incidents by count across zip codes: ['<6' '6' '0' '7' '9' '10' '8' '14' '35']
corresponding counts across zip codes: [23  7  5  4  3  2  2  1  1]
across quarter X2018Q1, percent of incidents < 6: 47.916666666666664

sorted incidents by count across zip codes: ['<6' '8' '0' '10' '6' '7' '9' '11' '12' '13' '17' '40']
corresponding counts across zip codes: [30  3  2  2  2  2  2  1  1  1  1  1]
across quarter X2018Q2, percent of incidents < 6: 62.5

sorted incidents by count across zip codes: ['<6' '0' '9' '10' '12' '6' '8' '20' '21' '48']
corresponding counts across zip codes: [30  4  3  2  2  2  2  1  1  1]
across quarter X2018Q3, percent of incidents < 6: 62.5

sorted incidents by count across zip codes: ['<6' '0' '6' '8' '15' '7' '10' '11' '12' '25' '36']
corresponding counts across zip codes: [25  6  5  3  2  2  1  1  1  1  1]
across quarter X2018Q4, percent of incidents < 6: 52.083333333333336

In [10]:
quarters = dph_od_resident_counts.columns[1:]

for q in quarters:
    unique_vals, counts = np.unique(dph_od_resident_counts[q].values, return_counts=True)
    
    count_sort_ind = np.argsort(-counts)
    
    print('sorted resident overdose by count across zip codes: {0}'.format(unique_vals[count_sort_ind]))
    print('corresponding counts across zip codes: {0}'.format(counts[count_sort_ind]))
    print('across quarter {0}, percent of incidents < 6: {1} \n'.format(q, 100*counts[count_sort_ind][0]/np.sum(counts[count_sort_ind])))

sorted resident overdose by count across zip codes: ['<6' '0' '6' '24' '7' '9']
corresponding counts across zip codes: [29 13  3  1  1  1]
across quarter X2014Q1, percent of incidents < 6: 60.416666666666664

sorted resident overdose by count across zip codes: ['<6' '0' '6' '9' '8' '11' '12' '20' '7']
corresponding counts across zip codes: [23 11  4  4  2  1  1  1  1]
across quarter X2014Q2, percent of incidents < 6: 47.916666666666664

sorted resident overdose by count across zip codes: ['<6' '0' '11' '7']
corresponding counts across zip codes: [32 12  3  1]
across quarter X2014Q3, percent of incidents < 6: 66.66666666666667

sorted resident overdose by count across zip codes: ['<6' '0' '8' '6' '10' '13' '14' '7']
corresponding counts across zip codes: [32  7  3  2  1  1  1  1]
across quarter X2014Q4, percent of incidents < 6: 66.66666666666667

sorted resident overdose by count across zip codes: ['<6' '0' '6' '8' '7' '10' '11' '20']
corresponding counts across zip codes: [26  9  5  3  2  1  1  1]
across quarter X2015Q1, percent of incidents < 6: 54.166666666666664

sorted resident overdose by count across zip codes: ['<6' '0' '6' '8' '9' '15' '7']
corresponding counts across zip codes: [29  9  3  3  2  1  1]
across quarter X2015Q2, percent of incidents < 6: 60.416666666666664

sorted resident overdose by count across zip codes: ['<6' '0' '10' '16' '6' '7' '8' '9']
corresponding counts across zip codes: [34  8  1  1  1  1  1  1]
across quarter X2015Q3, percent of incidents < 6: 70.83333333333333

sorted resident overdose by count across zip codes: ['<6' '0' '7' '6' '8' '11' '12' '19' '9']
corresponding counts across zip codes: [28  8  4  2  2  1  1  1  1]
across quarter X2015Q4, percent of incidents < 6: 58.333333333333336

sorted resident overdose by count across zip codes: ['<6' '0' '7' '9' '8' '12' '26']
corresponding counts across zip codes: [26  8  7  3  2  1  1]
across quarter X2016Q1, percent of incidents < 6: 54.166666666666664

sorted resident overdose by count across zip codes: ['<6' '0' '7' '10' '8' '19' '25' '6']
corresponding counts across zip codes: [33  5  3  2  2  1  1  1]
across quarter X2016Q2, percent of incidents < 6: 68.75

sorted resident overdose by count across zip codes: ['<6' '0' '6' '8' '10' '17' '28' '7' '9']
corresponding counts across zip codes: [33  4  3  3  1  1  1  1  1]
across quarter X2016Q3, percent of incidents < 6: 68.75

sorted resident overdose by count across zip codes: ['<6' '0' '7' '8' '11' '12' '16' '6' '9' '26' '44']
corresponding counts across zip codes: [22  6  5  3  2  2  2  2  2  1  1]
across quarter X2016Q4, percent of incidents < 6: 45.833333333333336

sorted resident overdose by count across zip codes: ['<6' '0' '6' '8' '10' '11' '7' '12' '14' '15' '20' '26' '38' '9']
corresponding counts across zip codes: [20  7  5  3  2  2  2  1  1  1  1  1  1  1]
across quarter X2017Q1, percent of incidents < 6: 41.666666666666664

sorted resident overdose by count across zip codes: ['<6' '0' '9' '6' '7' '12' '14' '8' '10' '13' '15' '35' '40']
corresponding counts across zip codes: [21  5  5  3  3  2  2  2  1  1  1  1  1]
across quarter X2017Q2, percent of incidents < 6: 43.75

sorted resident overdose by count across zip codes: ['<6' '0' '6' '7' '8' '9' '10' '12' '16' '30' '40' '41']
corresponding counts across zip codes: [26  5  3  3  3  2  1  1  1  1  1  1]
across quarter X2017Q3, percent of incidents < 6: 54.166666666666664

sorted resident overdose by count across zip codes: ['<6' '0' '7' '6' '8' '10' '21' '23' '33' '9']
corresponding counts across zip codes: [28  4  4  3  3  2  1  1  1  1]
across quarter X2017Q4, percent of incidents < 6: 58.333333333333336

sorted resident overdose by count across zip codes: ['<6' '0' '6' '7' '8' '10' '11' '13' '21' '42' '9']
corresponding counts across zip codes: [30  4  4  2  2  1  1  1  1  1  1]
across quarter X2018Q1, percent of incidents < 6: 62.5

sorted resident overdose by count across zip codes: ['<6' '0' '6' '9' '10' '7' '12' '15' '21' '40' '8']
corresponding counts across zip codes: [27  4  4  4  2  2  1  1  1  1  1]
across quarter X2018Q2, percent of incidents < 6: 56.25

sorted resident overdose by count across zip codes: ['<6' '0' '6' '9' '20' '7' '8' '16' '30' '40']
corresponding counts across zip codes: [28  5  3  3  2  2  2  1  1  1]
across quarter X2018Q3, percent of incidents < 6: 58.333333333333336

sorted resident overdose by count across zip codes: ['<6' '0' '7' '8' '9' '10' '14' '15' '20' '21' '35']
corresponding counts across zip codes: [23  7  7  3  2  1  1  1  1  1  1]
across quarter X2018Q4, percent of incidents < 6: 47.916666666666664

- bucketing?

In [11]:
print('unique incident zip codes:', dph_od_incident_counts['ZIPCODE'].unique())
print('unique resident zip codes:', dph_od_resident_counts['Zip.Code'].unique())

unique incident zip codes: ['19102' '19103' '19104' '19106' '19107' '19111' '19114' '19115' '19116'
 '19118' '19119' '19120' '19121' '19122' '19123' '19124' '19125' '19126'
 '19127' '19128' '19129' '19130' '19131' '19132' '19133' '19134' '19135'
 '19136' '19137' '19138' '19139' '19140' '19141' '19142' '19143' '19144'
 '19145' '19146' '19147' '19148' '19149' '19150' '19151' '19152' '19153'
 '19154' 'OOJ' 'Unknown']
unique resident zip codes: ['19102' '19103' '19104' '19106' '19107' '19111' '19114' '19115' '19116'
 '19118' '19119' '19120' '19121' '19122' '19123' '19124' '19125' '19126'
 '19127' '19128' '19129' '19130' '19131' '19132' '19133' '19134' '19135'
 '19136' '19137' '19138' '19139' '19140' '19141' '19142' '19143' '19144'
 '19145' '19146' '19147' '19148' '19149' '19150' '19151' '19152' '19153'
 '19154' 'OOJ' 'Unknown']

In [12]:
# drop OOJ, Unknown for now in incident and resident zip codes

In [13]:
kept_od_inc_zips = dph_od_incident_counts[~dph_od_incident_counts['ZIPCODE'].isin(['00J', 'Unknown'])]
kept_od_res_zips = dph_od_resident_counts[~dph_od_resident_counts['Zip.Code'].isin(['00J', 'Unknown'])]

- for simplicity, initial version is to first assign all nonzero incident/resident overdose counts as 1, whilst zero as 0.
- this boolean flagging approach will give us a rough sense of directionally how overdose locations move over time.

- current version- hardcoded threshold -> 10 to create mask.
- this effectively marks the regions which have 10 or more incidents per zip code while ignoring the rest.
- myopic in view, but intention is to see if high prevlance zips (as previously defined by threshold) change over time.

- Afterward, we can refine and pinpoint on top of this to show where the <6 incidents or higher are occurring

In [21]:
kept_od_inc_zips = kept_od_inc_zips.replace('<6', '0')
kept_zips = kept_od_inc_zips['ZIPCODE']
kept_zip_vals = kept_od_inc_zips.loc[:, kept_od_inc_zips.columns != 'ZIPCODE']

kept_zip_vals_numeric = kept_zip_vals.apply(pd.to_numeric)

kept_od_inc_zips = pd.concat([kept_zips, kept_zip_vals_numeric], axis=1)

In [32]:
# boolean flagging by overdose occurrence or not

def bool_flag_overdose_incidents(df, zipcode_col, threshold=0):
    """
    convert overdose counts above threshold to 1, whilst below threshold counts to 0
    
    * README:
    - not an automated function to use in bulk, just an exploration
    
    * current logic relies on creating a boolean mask to flag zip codes as areas which have
    incident counts above a certain threshold
    """
    vals = df[df.columns[df.columns != zipcode_col]]
    
    thresh_mask = (vals > threshold)
    bool_vals = vals.where(thresh_mask, other=0)

    df = pd.concat([df[zipcode_col], bool_vals], axis=1)
    
    return df 

bool_inc_zip_cts = bool_flag_overdose_incidents(kept_od_inc_zips, 'ZIPCODE', threshold=0)
# bool_res_zip_cts = bool_flag_overdose_incidents(kept_od_res_zips, 'Zip.Code')

In [33]:
bool_inc_zip_cts

,ZIPCODE,X2014Q1,X2014Q2,X2014Q3,X2014Q4,X2015Q1,X2015Q2,X2015Q3,X2015Q4,X2016Q1,...,X2016Q3,X2016Q4,X2017Q1,X2017Q2,X2017Q3,X2017Q4,X2018Q1,X2018Q2,X2018Q3,X2018Q4
0,19102,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,19103,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,19104,0,0,0,6,6,6,0,0,0,...,0,6,0,6,9,8,0,7,0,8
3,19106,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,19107,0,0,0,0,0,0,0,0,6,...,0,0,0,0,0,0,0,0,0,6
5,19111,0,0,0,0,0,0,0,0,7,...,8,0,9,11,0,6,6,0,8,0
6,19114,0,0,0,0,0,0,0,0,0,...,7,0,0,8,6,0,0,8,0,0
7,19115,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,6,0,0,0,0
8,19116,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,19118,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,19119,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,19120,0,0,0,7,6,0,0,0,0,...,8,7,8,10,0,0,0,0,10,6
12,19121,0,10,0,0,0,0,0,6,0,...,0,6,0,8,0,0,7,0,0,7
13,19122,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,6,0,0
14,19123,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,19124,9,10,10,8,7,11,9,8,10,...,9,10,24,17,26,25,14,12,20,25
16,19125,8,6,0,0,0,0,0,0,0,...,0,6,11,10,0,7,6,0,0,15
17,19126,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,19127,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,19128,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,6
20,19129,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,19130,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,19131,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,19132,6,0,0,8,13,7,0,7,7,...,8,13,8,9,7,11,8,10,0,7
24,19133,0,0,0,10,7,0,6,14,12,...,7,12,23,19,12,8,10,8,9,15
25,19134,15,18,19,22,19,23,30,21,22,...,39,52,53,59,61,36,35,40,48,36
26,19135,0,11,0,0,9,9,0,7,9,...,0,13,8,9,9,8,9,13,6,8
27,19136,0,8,0,0,10,8,0,0,7,...,7,11,9,7,7,8,8,11,10,0
28,19137,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,19138,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
30,19139,0,0,0,8,0,0,0,9,11,...,0,7,8,6,9,9,6,9,12,6
31,19140,7,10,6,10,0,10,9,12,7,...,6,9,13,21,8,10,9,17,12,11
32,19141,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,19142,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,0,0,0
34,19143,0,0,0,6,0,7,0,8,8,...,0,9,7,6,6,0,0,8,9,0
35,19144,0,8,6,0,0,0,0,6,7,...,0,0,6,0,0,6,6,0,9,0
36,19145,0,8,0,0,7,0,0,0,8,...,0,0,15,13,7,0,7,9,0,10
37,19146,0,0,0,0,0,0,0,0,0,...,0,0,8,0,11,0,0,0,0,0
38,19147,0,0,0,0,0,0,0,0,0,...,0,0,0,9,6,0,0,0,0,0
39,19148,6,7,0,0,9,0,0,10,7,...,7,17,9,13,14,7,10,10,21,12
40,19149,0,0,0,0,0,0,7,0,0,...,0,10,7,8,7,8,6,0,6,8
41,19150,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,19151,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,0,0,0
43,19152,0,0,0,0,0,0,6,0,0,...,7,7,7,8,9,6,9,0,8,0
44,19153,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,19154,0,0,0,0,0,0,0,0,0,...,0,6,7,6,9,8,6,0,0,0
46,OOJ,0,0,0,0,0,0,0,0,0,...,0,9,0,0,6,0,6,6,0,0

In [36]:
# execute for loop to create new folium Map() object and populate with the choropleth map data per iteration for every quarter

bool_inc_zip_cts['ZIPCODE']=bool_inc_zip_cts['ZIPCODE'].astype(str)

quarters = bool_inc_zip_cts.columns[1:]

for q in quarters:
    print('quarter:', q)
    map = fm.Map(location=[39.9526, -75.1652], default_zoom_start=15)
    
    map.choropleth(titles="Quarter {0}".format(q), geo_data=basepath+"Zipcodes_Philly_Polygon.geojson",
                 data=bool_inc_zip_cts[['ZIPCODE', q]], # my dataset
                 columns=['ZIPCODE', q],
                 key_on='feature.properties.CODE',
                 fill_color='BuPu', fill_opacity=0.4, line_opacity=0.4,
                 legend_name='Incident Overdose Counts by Zip, (incidents > 6)')

    # html file name
    html_filename = basepath+'output/{0}_Incident_Overdose_Occurrences_sup6.html'.format(q)
    
    map.save(html_filename)
    
    # use selenium to save .html to .png
#     print('html filename:', html_filename)
    
    png_filename = basepath+'output/{0}_Incident_Overdose_Occurrences_sup6.png'.format(q)
#     print('png filename:', png_filename)
    
    # use selenium to scrape from loaded HTML page
    driver = selenium.webdriver.PhantomJS(executable_path='/usr/local/bin/phantomjs')
    driver.set_window_size(600, 400)  # choose a resolution
    driver.get(html_filename)
    
    # You may need to add time.sleep(seconds) here
    time.sleep(3)
    
    driver.save_screenshot(png_filename)

quarter: X2014Q1
quarter: X2014Q2
quarter: X2014Q3
quarter: X2014Q4
quarter: X2015Q1
quarter: X2015Q2
quarter: X2015Q3
quarter: X2015Q4
quarter: X2016Q1
quarter: X2016Q2
quarter: X2016Q3
quarter: X2016Q4
quarter: X2017Q1
quarter: X2017Q2
quarter: X2017Q3
quarter: X2017Q4
quarter: X2018Q1
quarter: X2018Q2
quarter: X2018Q3
quarter: X2018Q4

# TODO: utilize ImageMagick (on Mac) or other off the shelf solution to create .gif from .pngs, .jpg images